@startuml クラス図


package Player{
class PlayerState{
+weapon
+hp
+ammo
+speed
}

class PLMove
class PLShot
class PLtouch

interface IKeyPad
class KeyPad

KeyPad --o IKeyPad
IKeyPad <- PLMove : ob
PlayerState <.left. PLShot : ob,write
PlayerState <.. PLMove : ob,write
PlayerState <.. PLtouch : write
}

interface Itouchable
Itouchable .> PLtouch : 接触処理


package Weapon{
    class weapon
    
    class bullet{
        +Init
        +Shot
        +SonotaMoromoro
    }
    
    class weaponState{
        +speed
        +bullet
        +MaxAmmo
        +andmore
    }

    class PlayersBullet
    weapon *-- bullet
    weapon *-- weaponState
    weaponState<-left- bullet : 値参照
    bullet <|-- EnemyBullet
    Itouchable <|.Up. EnemyBullet
    bullet <|-- PlayersBullet
    Itouchable .Up.> PlayersBullet :接触処理 

}



package Enemy{
    class TekiMove
    class TekiTouch
    class TekiShot
    class TekiAI
    class TekiState

    TekiState <.. TekiMove
    TekiAI <.. TekiMove
    TekiState <.. TekiTouch
    TekiState <.. TekiShot
    Itouchable <|. TekiTouch
    TekiState *-- EnemyBullet 
}

package GameDealer{
    class datalog
    class UIWriter

    PlayerState <-Up- datalog : ob
    datalog <- UIWriter : ob

}

@enduml